### ISSUE TITLE
get-msolserviceprincipal works only for *home* tenant

### ISSUE THREAD

**Issue by mprabhu11** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#1]
It would be very helpful to add a note that when calling the get-msolserviceprincipal cmd-let, the caller must be logged in using a **native** admin account in the corresponding AAD. 

I am a regular user in my corporate AAD and -- because I created my experimental XYZ tenant while logged in via my corp account, my corp account is also a global admin in this tenant. I ended up spending quite some time trying to figure out why it wouldn't let me do any of the serviceprincipal operations in the XYZ tenant. Finally, I had to create a native (local) account in XYZ and add _that_ account to the global admins. Then, having logged in using that account, I could run the cmd-lets successfully.

Please add a note about this to the document for this sample. (Basically saying that this is an admin operation and admin operations are supported only using a native account for the tenant.)

If you can, please also have the party that owns the doc at the link below add a "Note:" about this so that it can benefit an even broader audience:
http://technet.microsoft.com/library/jj151815.aspx  

(A related request - it would also be handy to have a cmd-let that returns the tenantId of the tenants which the logged in user is associated with. :-) )

By the way, this sample is very neat. Helped me learn a lot of interesting things.

**Comment by aluong** [comment]
Thanks for tip! Definitely not intuitive.

**Comment by jmprieur** [comment]
Closing this issue as it's no longer relevant to the sample (which now does no longer use this cmd-let)
