### ISSUE TITLE
Certificate vs Client Secret flow

### ISSUE THREAD

**Issue by amit777** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#11]
So I finally have basic examples of both Certificate and Client secret token requests working using our organization's tenant. Now I'm trying to figure out why use one vs the other?  Is it just a matter of taste or security policy to choose the secret vs certificate flow?  Or are their functional or usability differences?

**Comment by dstrockis** [comment]
There aren't any functional differences per se... It's mostly a tradeoff between management overhead/ease of use and security.  For some applications a shared secret will be perfectly sufficient, while others will have strict security policies in place.

The one usability difference I can think of is that at this time you can manage client secrets in the Azure Portal, while certifcate mgmt must be done through powershell or through the application manifest.
