### ISSUE TITLE
Uploading daemon certificate to Azure AD

### ISSUE THREAD

**Issue by ElDiabloComputatore** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#13]
Hi!

I've been playing with this sample later in December before latest commit (ee79f1c). Uploading certificate using Azure AD module for Powershell was removed in that latest commit and it was replaced by changing manifest of application.
Here is the question: when (or how) is the daemon certificate uploaded to Azure AD? I think there is missing step or is it only my limited knowledge?

**Comment by dstrockis** [comment]
Hey - It occurs in this step: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential#add-the-certificate-as-a-key-for-the-todolistdaemonwithcert-application-in-azure-ad

When you upload the manifest back into the portal, the cert if uploaded as well.

**Comment by ElDiabloComputatore** [comment]
Ok, thanks, I got it (eventually) :)
