### ISSUE TITLE
What claim type map with KeyId or customKeyIdentifier

### ISSUE THREAD

**Issue by ravisankar-krinik** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#18]
Hi 

First of all thanks for this post, this helps me really lot in taking decision on implementing OAuth 2.0 client credential grant to our API.

I have multiple customer accessing same API using client credential flow. This solution works very well by adding array of  keyCredentials in manifest file. But how do i uniquely identify the customer at Web API side. I was looking for claims whether KeyId or customKeyIdentifier are populated but i can't find it.

Is there anyway I get KeyId or customKeyIdentifier at Web API or what is the best solution for my requirement.

Thank you

Kind Regards
Ravisankar

**Comment by jmprieur** [comment]
@ravisankar-krinik ; I don't think you'll get the keyId or customKeyidentifier indeed. Would it work with just the thumbprint of the certificate?
