### ISSUE TITLE
Use New-SelfSignedCertificate instead of makecert (makecert is deprecated)

### ISSUE THREAD

**Issue by epawlowska** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#20]
makecert is deprecated: https://msdn.microsoft.com/en-us/library/windows/desktop/aa386968(v=vs.85).aspx

**Comment by jmprieur** [comment]
Resolved by https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/commit/9ec67e7ec6e23ebb0530fa70860d952a76975396
