### ISSUE TITLE
 Associate the certificate credential using new portal.azure.com

### ISSUE THREAD

**Issue by Rafa5** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#21]
We  try to do this using portal.azure.com, creating a certificate and modifying Manifesto (inserting appropiate keys into "keyCredentials").
But after obtain an Access Token, when doing the request to operation (for example, send a mail) the response obtained was " Access is denied. Check credentials and try again."

 We don't have an Azure subscription, so we can't access the classic Azure management portal.

Any suggestions?

**Comment by jmprieur** [comment]
@Rafa5: I believe that this will be resolved by https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/commit/9ec67e7ec6e23ebb0530fa70860d952a76975396. Feel free to re-open if this does not work for you
