### ISSUE TITLE
What is "Client ID"

### ISSUE THREAD

**Issue by eanders-MS** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#28]
Hello. I'm working through the setup instructions in the README. Section [step-3--configure-the-sample-to-use-your-azure-ad-tenant](https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential#step-3--configure-the-sample-to-use-your-azure-ad-tenant) states:
```
Find the app key ida:ClientId and replace the value with the Client ID for the TodoListDaemonWithCert app registration from the Azure portal.
```
But I see no attribute or setting on my created TodoListDaemonWithCert app called `Client ID`. Am I just missing it? Or is this the same as Application ID?

**Comment by jmprieur** [comment]
You are right @eanders-MS : it's no longer needed. BTW, I'm working on a script which automates everything (see the currently opened PR). I'll fix this as well.

**Comment by jmprieur** [comment]
@eanders-MS : just to make sure we are aligned, there is still a ida:ClientID in the TodoListDaemonWithCert App.config file. 
And indeed, this is the Application Id of the daemon application.
Where it's no longer needed is in the TodoListService's App.Config.

**Comment by eanders-MS** [comment]
Understood, thank you for the clarification. It might be worth being explicit about this in the README's instructions.

**Comment by eanders-MS** [comment]
Also, so grateful for these sample projects... super helpful to gain some understanding of this arcane world of AAD auth. Thank you for them.
