### ISSUE TITLE
Cannot add keyCredentials to manifest

### ISSUE THREAD

**Issue by eanders-MS** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#30]
Hello, I'm attempting to follow the detailed instructions. I'm attempting to add my generated keyCredentials to my TodoListDaemonWithCert AD app, but it won't let me specify a non-null value for the `value` field:

![image](https://cloud.githubusercontent.com/assets/12176807/23772716/dfcb7288-04d0-11e7-874b-7a2818e82372.png)

When I try to save, I see this:

![image](https://cloud.githubusercontent.com/assets/12176807/23772670/b95ffd1c-04d0-11e7-881e-808430de4e0c.png)

If I set the `value` field to null, it will accept the edit.

How can I set the value of the keyCredentials?

**Comment by eanders-MS** [comment]
I think it's just bad UI design. What I *think* is happening is the value is immutable, and not displayed back to the user when reopening the manifest. But it is stored for `keyId` somewhere.

**Comment by jmprieur** [comment]
@eanders-MS: I was also confused by the UX.
What you need to do is to replace the key completely (not the value) by the snippet shown in the documentation (in the manual steps .md). In other words:
- you write a json snippet in the editor (in particular with your value)
- when you save you see something completely different. Note that the dates are infered by the content of the certificate
