### ISSUE TITLE
Need your Help - Unable to execute .\Configure.ps1 script in Powershell

### ISSUE THREAD

**Issue by debstf** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#35]
Hi,

Please help me. Unable to execute .\Configure.ps1 script in Powershell to create the environment for AAD. Please find below the error -

**C:\GitHub\DOTNETCORE\Configure.ps1 : Cannot process argument transformation on 
parameter 'Credential'. Cannot convert the "XXXXXXXXXXXXXXX" value of type "System.String" 
to type "System.Management.Automation.PSCredential".
At line:1 char:17
.\Configure.ps1 XXXXXXXXXXXXXXXXXXXXXXX
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [Configure.ps1], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Configure.ps1**

//Marked the Tenant ID as XXXXXXXXXXXXXXX

Followed the below steps in Powershell as mention in Configure.ps1-
Install-Module AzureAD  // Executed successfully
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process  //Executed successfully
$apps = ConfigureApplications -XXXXXXXX //Failed. Error is -
ConfigureApplications : The term 'ConfigureApplications' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:9
 $apps = ConfigureApplications -XXXXXXXXXXXXX
         ~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (ConfigureApplications:String) [], CommandNotFoundException
    FullyQualifiedErrorId : CommandNotFoundException
 
Thanks.

Best Regards,
Deb

**Comment by jmprieur** [comment]
@debstf : If you want to pass the credentials directly to the script, I suggest you do the following:
```
$secpasswd = ConvertTo-SecureString "XXXX your password XXXXX" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential (“YOUR_LOGIN@YOUR_DOMAIN.onmicrosoft.com”, $secpasswd)
. .\Configure.ps1 -Credential $mycreds
````
of course replacing the password and login strings by your own.

**Comment by debstf** [comment]
@jmprieur : Thanks. But again I am facing issue which related with Windows Graph. Issues  is - 
AADSTS50034: To sign into this application the account must be 
added to the graph.windows.net directory.
Trace ID: 362c802d-33f2-487b-92ed-9ba12cb50300
Correlation ID: 230bc6c8-a2d8-4d44-b0c9-dffa67c9f013

**Comment by jmprieur** [comment]
@debstf : I'm not sure how one can access the graph without being in the name of a user. What is your scenario?

**Comment by debstf** [comment]
@jmprieur : I am not accessing Graph. Want to create the Apps in Azure Active Directory through Powershell [sample attached in this repository - active-directory-dotnet-daemon-certificate-credential]. Executing "**Configure.ps1**" script from this repository.

**Comment by jmprieur** [comment]
@debstf : Can you tell me a bit more about the user you use to add the application to the active directory? Is it an admin of this AAD?

**Comment by debstf** [comment]
@jmprieur Yes, the user is Global Administrator. Please tell me If I need to create any other user for this.

FYI - I can do the Apps manually from the Portal, just I am trying it with Powershell script.

**Comment by debstf** [comment]
@jmprieur  I created the apps manually and it's working. Will try the Powershell script later. 
Thanks.

Best Regards,
Deb
