### ISSUE TITLE
How to deploy this sample to Azure?

### ISSUE THREAD

**Issue by Rulikkk** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#36]
I will need to deploy similar app to azure.
Please assist on the list of configuration steps:

1. Upload certificate to Azure App Service (Settings -> Certificates)
2. Configure app to use that certificate: add cert's thumbprint to some config file (Don't know where it is yet)

Does this look like a full list? Am I missing something?

**Comment by jmprieur** [comment]
Hello @Rulikkk : the configuration steps are explained in https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/Manual-Configuration-Steps.md.
this is a console application, would that work with app service? 
If it does you might want to store the certificate in KeyVault, and deploy it from there: https://blogs.msdn.microsoft.com/appserviceteam/2016/05/24/deploying-azure-web-app-certificate-through-key-vault/
