### ISSUE TITLE
Can't run New-SelfSignedCertificate

### ISSUE THREAD

**Issue by einarc** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#37]
> yAlgorithm RSA -KeyLength 2048 -NotAfter (Get-Date).AddMonths(6)
> New-SelfSignedCertificate : A parameter cannot be found that matches parameter name 'Type'.
> At line:1 char:27
> + New-SelfSignedCertificate -Type Custom -Container test* -Subject "CN=Patti Fulle ...
> +                           ~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [New-SelfSignedCertificate], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCo
>    mmand

Running on Windows 2012

Neither following these instructions:
https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps

**Comment by einarc** [comment]
Solved: https://stackoverflow.com/questions/35924054/new-selfsignedcertificate-on-win2012-r2-has-less-parameters#35924560

**Comment by einarc** [comment]
Actually, after reading this, please update the code saying that Windows 2012 doesn't really support your instructions.

**Comment by jmprieur** [comment]
Done.
