### ISSUE TITLE
Is it possible to store the token in cache and renew with refresh token?

### ISSUE THREAD

**Issue by nigel-dewar** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#38]
Hi,

Is it possible once you have acquired the token , to store in cache and renew using refresh token?

this is using this

AuthenticationResult authenticationResult = null;
authenticationResult = await authenticationContext.AcquireTokenAsync(service, cac);

I have noticed whilst making the initial call to get the token, a refresh token is NOT included.
Why is the refresh token not included? Is this by design?

Im using ADAL v3.14 by the way in a .net core console
 <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.14.0" />

With my code I am doing, the cache is being accessed, but my application seems to ignore it, and makes a call to get a brand new token from azure AD every time, which takes A LONG time vs getting its non-expired token from cache. Like, sometimes up to 10 seconds!!! 

Its like it looks in cache, sees it has a token, ignores it and then goes and gets another fresh token! I thought the token cache was supposed to negate the need for this.

Is it not possible to use cache with this type of scenario?

If it is, how would one use something like AquireTokenSlightAsync with this?  ( after getting the AquireTokenAsync initial call of course) ?

I noticed with AcquireTokenSilentAsync it expects some kind of user identifier, so I have tried things like this

UserIdentifier userIdentifier = new UserIdentifier(tenantId, UserIdentifierType.RequiredDisplayableId);
authenticationResult = await authenticationContext.AcquireTokenSilentAsync(service, cac, userIdentifier);

But to no avail, can you let me know if the token cache even works for a daemon/certificate scenario or does ADAL just want to go get a new token from Azure AD, everytime and ignore its cache?

**Comment by jmprieur** [comment]
@nigel-dewar : which authority do you use? would you be in a multi-tenant case?

**Comment by jmprieur** [comment]
I suggest you have a look at [Token cache serialization](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization)
and [Recommended pattern to acquire a token](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token)
