### ISSUE TITLE
Maximum Credential Time Span of 2 Years

### ISSUE THREAD

**Issue by mprabhu11** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#4]
Attempting to run the below cmd-let:
New-MsolServicePrincipalCredential -tenantId "25fc..." -AppPrincipalId "697c..." -Type asymmetric -Value $cred -StartDate $cer.GetEffectiveDateString() -EndDate $cer.GetExpirationDateString() -Usage verify

fails with: 
New-MsolServicePrincipalCredential : Invalid value for parameter.  Parameter
name: Credential.EndDate.
At line:1 char:1

I tried manually providing the date-time string as well (using the value returned by $cer.GetExpirationDateString()) but even _that_ does not make it happy. I can feed a slightly _earlier_ time to -EndDate and then it works. However, that does not eventually help because when the sample is run, signature validation fails. :-( 

It seems like a timezone type issue...that too only for the EndDate parameter. These are the StartDate and EndDate values of the cert I am using: 6/15/2014 4:56:12 PM, 6/15/2016 4:56:11 PM (I am in IST). 

I actually got this to work somehow but don't recollect how (darn, should have written down the final command that worked... :-(). 

(**Edit:** Figured it out. It was by _not_ providing the StartDate, EndDate tuple at all. Then it seems to take them from the cert date. Duh! :-) However, there still seems to be a DST issue. My cert's IST expiration time is 4:56 PM, that should have been 12:26PM GMT as it is summer. However, it shows as 11:26AM GMT (which would be okay in winter) when I run Get-MsolServicePrincipalCredential.)

However, I also wonder why this cmd-let wants to get these parameters separately when it is also getting the entire raw certificate. Can't it pick these up form the cert data (and have a higher assurance of their authenticity as well)? Secondly, the fact that AAD uses _these_ values subsequently for signature validation part is even more baffling/worrisome...as I believe the effective and expiration dates are supposed to be included in the authenticated blob inside a cert and any security validation should read them from there (and not from any other extraneous source). (Note that this is based on the observation that I could feed a slightly early-PM or AM expiration date and get the cmd-let to accept the certificate -- however the client_credential flow fails with invalid signature.)

**Comment by wakurth** [comment]
An alternate fix is to ensure the "-End" date is not longer that 2 years out from the "-Start". There's seem to be a max time span.

**Comment by jmprieur** [comment]
Closing this issue as the example does no longer use New-MsOlServicePrincipalCredential
