### ISSUE TITLE
Is it possible to use certificates tied to real Azure AD account vs service principal

### ISSUE THREAD

**Issue by artisticcheese** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#41]
Hello,

I have a requirement to use Azure Active Directory user for authentication, vs using service principal. Is it possible to use certificate based authentication in such cases?

**Comment by jmprieur** [comment]
It is possible but this is a different scenario. 
Are you building a Web app? or a Mobile desktop app?
Depending the answer to this question, you'll need to use one or the other of these flows described in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo.

you might also want to have a look at the page describing all the available samples for ADAL(.NET): 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-code-samples
