### ISSUE TITLE
Confusing "Register the client app" in readme.md

### ISSUE THREAD

**Issue by subhadipg** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#43]
When registering the TodoListDaemon, Step 2 mentions that this is a web application and not a native application. However (Step 3) Redirect URI is only present for the "native app" selection. If we go down the native application route however, App ID Uri cannot be changed.

Is this intended to be a web application and should step 3 use "sign on" url instead of "redirect" url?

**Comment by jmprieur** [comment]
Thanks for reporting, @subhadipg. you are right the step 3 requires using "sign-on URL". I just fixed the readme.md
