### ISSUE TITLE
Roles & Custom Claims

### ISSUE THREAD

**Issue by mixxit** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#45]
Is it possible you can update this documentation to include custom roles as claims for certificate credentials?

Also custom claim values for a specific app registration?

**Comment by mixxit** [comment]
It seems you can assign this to your application manifest for TodoListService to create a new role that you can assign in Required Permissions in your ToDoListDaemon (click grant all)

```
"appRoles": [
    {
      "allowedMemberTypes": [
        "User",
        "Application"
      ],
      "displayName": "TodoListService.Write",
      "id": "6b2c7228-d8e4-462a-ba87-641e14dbbb23",
      "isEnabled": true,
      "description": "Allows write access to TodoListService",
      "value": "Writer"
    }
  ]
```

Then in your TodoListService you can add 

```
            services.AddAuthorization(options =>
            {
                options.AddPolicy("RequireRoleTodoListService.Write", policy => policy.RequireClaim("http://schemas.microsoft.com/ws/2008/06/identity/claims/role", "TodoListService.Write"));
            });
```

Then you can append this attribute to your controllers

[Authorize(Policy = "RequireRoleTodoListService.Write")]

**Comment by mixxit** [comment]
I am just struggling now to find how to associate custom claims to an application credential

I believe normally this would be done via User active directory extensions but i am not certain how to achieve this for certificate auth

Can anyone advice or update this example project?

**Comment by kalyankrishna1** [comment]
Have you looked at this preview feature (https://docs.microsoft.com/en-us/azure/active-directory/active-directory-claims-mapping)

**Comment by kalyankrishna1** [comment]
@mixxit , do you have remaining questions ? OR shall we proceed to close this issue?

**Comment by TiagoBrenck** [comment]
@mixxit we have just included AppRoles in this sample.

**Comment by jmprieur** [comment]
Archiving this sample in favor of the v2.0 sample
