### ISSUE TITLE
AADSTS70002: Error validating credentials. AADSTS50012: Client assertion is not within its valid time range.

### ISSUE THREAD

**Issue by pawelsberg** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#46]
I followed the "How to run this sample". And I have an error when running:
AADSTS70002: Error validating credentials. AADSTS50012: Client assertion is not within its valid time range.

The line throwing an error is (Program.cs(147)):
result = await authContext.AcquireTokenAsync(todoListResourceId, certCred);

Help appreciated.

**Comment by jmprieur** [comment]
@pawelsberg : 
which certificate did you use?  Are you sure you have not an old certificate?

did you try following this: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/AppCreationScripts/AppCreationScripts.md
this should create a certificate for you.

**Comment by pawelsberg** [comment]
Thanks for a quick response. I created the certificate using:

$cert=New-SelfSignedCertificate -Subject "CN=TodoListDaemonWithCert" -CertStoreLocation "Cert:\CurrentUser\My"  -KeyExportPolicy Exportable -KeySpec Signature

X509Certificate2 has been issued today for a year. NotBefore and NotAfter range contain the time I was running the test (checked in debugger).

I have not tried AppCreationScripts. I plan to do it tomorrow.

I am thinking - maybe it has something to do with timezone of the azure servers and it will start working tomorrow? My timezone is GMT.

**Comment by jmprieur** [comment]
Thanks for the update. 
We'll check with AAD.
@henrik-me FYI

**Comment by jmprieur** [comment]
Archiving this sample in favor of the v2.0 sample
