### ISSUE TITLE
Instructions for securing app-service API in Azure UI?

### ISSUE THREAD

**Issue by Dev-Mom** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#48]
All of the samples I've seen for Azure app-only authentication of a web API are securing it using code in the project.
>  
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidAudience = ConfigurationManager.AppSettings["ida:Audience"]
                    }
                });
>

However, if I were to use the Azure interface for securing the API - how would I do so?  
Is this the correct process?
https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication#a-nameadvanced-aalternative-method-manually-configure-azure-active-directory-with-advanced-settings

**Comment by TracyGH** [comment]
Hi @kalyankrishna1 - I am looking for guidance on configuring Easy Auth for app-only/identity/daemon app authentication.  Basically, the UI equivalent of this:  https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-daemon-certificate-credential/.

Can you point me towards such documentation?  
Thank-you!
