### ISSUE TITLE
Why there are so many manual steps?

### ISSUE THREAD

**Issue by goroyal** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#49]
If a user needs to create multiple key vaults and Azure Active Directory tenant, he/she may do much repeating work and it is easy to make mistakes.

**Comment by kalyankrishna1** [comment]
@goroyal Have you had a chance to look into the automation sample provided in the AppcreationScripts folder? If you work with multiple tenants, certs  and applications, you should consider making use of the scripts to avoid mistakes possible due to manual work
