### ISSUE TITLE
Manifest update

### ISSUE THREAD

**Issue by piotrsogeti** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#56]
I have followed the example, along with Pluralsight course that seems to be doing the same and when I try to save the manifest with powershell generated content put into
keyCredentials:
[
    {
        "keyId":  "my-id-was-here",
        "value":  "my-cert-was-here",
        "type":  "AsymmetricX509Cert",
        "usage":  "Verify",
        "customKeyIdentifier":  "my-key-was-here"
    }
]I get this:
Failed to update DaemonCertConsoleApp application. Error detail: Upload a certificate (public key) with one of the following file types: .cer, .pem, .crt [xvAU9]

Also since Azure App registration portal got updated some of the steps need update too.

**Comment by jmprieur** [comment]
@piotrsogeti 
I'll try to understand what happens at the end of the week.

Meanwhile, I recommend you use the new samples for the Microsoft identity platform v2.0:
https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2

**Comment by jmprieur** [comment]
Archiving this sample in favor of the v2.0 sample
