### ISSUE TITLE
Multitenant App Cert Unauthorized

### ISSUE THREAD

**Issue by aluong** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#8]
I have two AAD tenants. I registered my client app with Tenant-1.
When I use the certificate authorization flow only users from Tenant-1 are able to authenticate.
When I try to use the certificate authorization flow with users from Tenant-2, I get a "401 Unauthorization".

Note: When I use the clientId and client secret authorization flow with this same client app, it authenticates users from either tenants.

**Comment by dstrockis** [comment]
Could you provide the error message or a trace of the failing request?
