### ISSUE TITLE
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

### ISSUE THREAD

**Issue by wakurth** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#9]
I'm seeing this error on the last line of this code block

``` cSharp
ClientAssertionCertificate credential = certificateFactory.GetCertificateCredential();

AuthenticationContext authContext = new AuthenticationContext(settings.Authority,
                    new NaiveSessionCache(userObjectIdentifier, cacheManager));

// error is throw here
AuthenticationResult result = authContext.AcquireToken(settings.GraphUrl, credential);
```

After a little Google-Foo, I found [this article](http://blog.johnruiz.com/2012/01/invalid-provider-type-specified-when.html)

It's not specific to this this library, but seem to be what all articles I found around this error point to.

To summarize, it seems this error happens when using certificates generated with Microsoft's new Cryptography Next Generation (CNG) based templates. I haven't read through the source code, but I'm assuming it's using the older .NET 3.5 base objects for handling certificates, and not the new .NET 4 managed implementations for CNG. 

Are there any plans to support CNG based certificates in [this](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory) library?

**Comment by jmprieur** [comment]
Thanks for your feedback, @wakurth 
I also had this problem when generating the certificate **without** the `-KeySpec Signature` option.
```
$cert=New-SelfSignedCertificate -Subject "CN=TodoListDaemonWithCert" -CertStoreLocation "Cert:\CurrentUser\My"  -KeyExportPolicy Exportable -KeySpec Signature
```
Adding that option solved the problem.

**Comment by darcythomas** [comment]
I may have a fix for this I'll make a pull request tonight if I can.

**Comment by jmprieur** [comment]
Hi @darcythomas. 
you mean you still experience the problem with the current Readme.md ? Which kind of fix do you have? a fix for the readme.md?

**Comment by jmprieur** [comment]
We don't support the elliptic algorithm yet. Will add to the backlog for AAD.

**Comment by wakurth** [comment]
It's nice that you're acknowledging the issue now. The biggest issue was our premier Azure support informed us we could "make the certificates however we want"... that one thing sent us in circles. It's all about proper and consistant information. Again, I'm glad you are adding it to the backlog.
